version: "2"
checks:
  method-complexity:
    config:
      threshold: 8
plugins:
  checkstyle:
    enabled: true
    config:
      file: "config/checkstyle/checkstyle.xml"
  duplication:
    enabled: true
    config:
      languages:
        java:
          mass_threshold: 50
  editorconfig:
    enabled: true
    channel: beta
