plugins:
  checkstyle:
    enabled: true
    config:
      file: "config/checkstyle/checkstyle.xml"
  editorconfig:
    enabled: true
    channel: beta
  pmd:
    enabled: true
    config:
      file: "config/pmd/ruleset.xml"
