version: "2"
checks:
  method-complexity:
    config:
      threshold: 8
engines:
  duplication:
    enabled: true
    config:
      languages:
        java:
          mass_threshold: 50
plugins:
  checkstyle:
    enabled: true
    config:
      file: "config/checkstyle/checkstyle.xml"
  editorconfig:
    enabled: true
    channel: beta
  pmd:
    enabled: true
    config:
      file: "config/pmd/ruleset.xml"
